-- DBPilot 平台库建表脚本（PostgreSQL 13+，幂等：CREATE TABLE IF NOT EXISTS + CREATE INDEX IF NOT EXISTS 独立语句）
-- 与 scripts/database/sqlserver/schema.sql 逐表逐列对应（V4.0 §6.9）
-- 由 PostgreSqlSchemaInitializer 在启动时执行（EmbeddedResource，按分号切批）
-- 脚本约定：字符串与注释中一律不出现分号
-- 口径：时间列 timestamptz（存即时值，Npgsql 往返即 Kind=Utc，免 MySQL 墙钟/SS 3.33ms 网格负担）；
-- 布尔位 INTEGER 1/0 → BOOLEAN；超长文本 → TEXT；自增 → GENERATED BY DEFAULT AS IDENTITY（Chloe 插列不指 id，两形态均兼容）

CREATE TABLE IF NOT EXISTS dbpilot_instance (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(100)  NOT NULL,
    host                    VARCHAR(256)  NOT NULL,
    port                    INTEGER       NOT NULL DEFAULT 1433,
    engine                  VARCHAR(16)   NOT NULL DEFAULT 'sqlserver',  -- 引擎：sqlserver / mysql / postgresql
    login_name              VARCHAR(64)   NOT NULL,
    password_cipher         VARCHAR(512)  NOT NULL,          -- AES-GCM（§5.7）
    enabled                 BOOLEAN       NOT NULL DEFAULT TRUE,
    status                  INTEGER       NOT NULL DEFAULT 0,  -- 0未知 1在线 2退避 3离线
    server_version          VARCHAR(32)   NULL,
    major_version           INTEGER       NULL,              -- 10=2008, 10.5=2008R2, 11=2012...
    edition                 VARCHAR(64)   NULL,              -- R5 版别判断
    cpu_cores               INTEGER       NULL,              -- vCores 参考线
    machine_name            VARCHAR(128)  NULL,
    sqlserver_start_time    TIMESTAMPTZ   NULL,              -- 实例启动时间（tempdb create_date / postmaster_start_time），重启检测
    clock_skew_seconds      INTEGER       NOT NULL DEFAULT 0,
    xe_file_path            VARCHAR(256)  NULL,              -- XE 文件目录
    slow_sql_threshold_ms   INTEGER       NOT NULL DEFAULT 1000,
    blocking_threshold_sec  INTEGER       NOT NULL DEFAULT 5,
    env_tag                 VARCHAR(50)   NULL,              -- 生产/测试，仅展示
    db_filter               TEXT          NULL,              -- JSON：库白/黑名单
    last_error              VARCHAR(500)  NULL,
    last_heartbeat          TIMESTAMPTZ   NULL,
    create_time             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    update_time             TIMESTAMPTZ   NULL,
    CONSTRAINT uq_dbpilot_instance_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS dbpilot_sql_template (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id   INTEGER       NOT NULL,
    fingerprint   VARCHAR(64)   NOT NULL,      -- query_hash hex 或归一化文本哈希
    sql_text      TEXT          NOT NULL,
    first_seen    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    last_seen     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_dbpilot_tpl UNIQUE (instance_id, fingerprint)
);

CREATE TABLE IF NOT EXISTS dbpilot_active_request_sample (    -- 分钟聚合；10s 原始样本仅内存
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id           INTEGER       NOT NULL,
    minute_time           TIMESTAMPTZ   NOT NULL,   -- 整分（UTC）
    sample_count          INTEGER       NOT NULL,
    avg_active_sessions   NUMERIC(9,2)  NOT NULL,
    max_active_sessions   INTEGER       NOT NULL,
    buckets               TEXT          NOT NULL,   -- {"cpu":0.21,"userIo":0.03,...}
    dims                  TEXT          NOT NULL,
    create_time           TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dbpilot_top_sql_delta (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id          INTEGER       NOT NULL,
    fingerprint          VARCHAR(64)   NOT NULL,
    db_name              VARCHAR(128)  NULL,             -- 计划编译库上下文（ad hoc 可能 NULL）；历史按库筛选
    window_start         TIMESTAMPTZ   NOT NULL,
    window_end           TIMESTAMPTZ   NOT NULL,
    exec_count           BIGINT        NOT NULL,
    total_worker_ms      BIGINT        NOT NULL,
    total_elapsed_ms     BIGINT        NOT NULL,
    total_logical_reads  BIGINT        NOT NULL,
    total_physical_reads BIGINT        NOT NULL,
    total_writes         BIGINT        NOT NULL,
    max_elapsed_ms       BIGINT        NOT NULL,
    create_time          TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dbpilot_slow_sql (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id     INTEGER       NOT NULL,
    event_time      TIMESTAMPTZ   NOT NULL,     -- 已按平台 UTC 校正
    db_name         VARCHAR(128)  NULL,
    login_name      VARCHAR(128)  NULL,
    host_name       VARCHAR(128)  NULL,
    app_name        VARCHAR(256)  NULL,
    session_id      INTEGER       NULL,
    sql_type        INTEGER       NOT NULL,     -- 1=rpc 2=batch
    duration_ms     BIGINT        NOT NULL,
    cpu_ms          BIGINT        NULL,
    logical_reads   BIGINT        NULL,
    physical_reads  BIGINT        NULL,
    writes          BIGINT        NULL,
    row_count       BIGINT        NULL,
    fingerprint     VARCHAR(64)   NULL,
    sql_text        TEXT          NOT NULL,
    create_time     TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dbpilot_deadlock_event (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id        INTEGER       NOT NULL,
    event_time         TIMESTAMPTZ   NOT NULL,
    victim_spids       VARCHAR(100)  NOT NULL,     -- 逗号分隔
    fingerprint        VARCHAR(64)   NOT NULL,      -- 图哈希，去重/相似归并
    deadlock_graph     TEXT          NOT NULL,      -- 原始 XML 全文（事实源，详情重解析）
    utc_offset_minutes INTEGER       NOT NULL DEFAULT 0,  -- 采集时实例本地-UTC（分钟）
    create_time        TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- 死锁进程维度（一事件 N 行：SPID 行级明细 + 登录/主机维度的分析统计）
CREATE TABLE IF NOT EXISTS dbpilot_deadlock_process (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id          INTEGER       NOT NULL,
    instance_id       INTEGER       NOT NULL,
    event_time        TIMESTAMPTZ   NOT NULL,       -- 冗余：清理/统计免 JOIN
    spid              INTEGER       NOT NULL,
    is_victim         BOOLEAN       NOT NULL,
    login_name        VARCHAR(200)  NULL,
    host_name         VARCHAR(100)  NULL,
    client_app        VARCHAR(200)  NULL,
    isolation_level   VARCHAR(60)   NULL,
    lock_mode         VARCHAR(10)   NULL,
    wait_resource     VARCHAR(500)  NULL,
    status            VARCHAR(30)   NULL,
    transaction_name  VARCHAR(60)   NULL,
    log_used          INTEGER       NOT NULL DEFAULT 0,   -- KB
    wait_time_ms      INTEGER       NOT NULL DEFAULT 0,
    trancount         INTEGER       NOT NULL DEFAULT 0,
    last_tran_started TIMESTAMPTZ   NULL,           -- UTC（采集时已按实例时区转换）
    input_buf         TEXT          NULL,           -- 完整 SQL（inputbuf 全文）
    create_time       TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- 死锁资源维度（一事件 M 行：锁类型趋势 / 对象维度分析）
CREATE TABLE IF NOT EXISTS dbpilot_deadlock_resource (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      INTEGER       NOT NULL,
    instance_id   INTEGER       NOT NULL,
    event_time    TIMESTAMPTZ   NOT NULL,           -- 冗余：趋势 GROUP BY / 清理免 JOIN
    resource_type VARCHAR(30)   NOT NULL,           -- keylock/objectlock/pagelock/ridlock/exchangeEvent...
    object_name   VARCHAR(400)  NULL,
    index_name    VARCHAR(200)  NULL,
    lock_mode     VARCHAR(10)   NULL,
    create_time   TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dbpilot_blocking_event (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id      INTEGER       NOT NULL,
    head_session_id  INTEGER       NOT NULL,
    start_time       TIMESTAMPTZ   NOT NULL,
    end_time         TIMESTAMPTZ   NULL,
    blocked_count    INTEGER       NOT NULL,
    max_wait_seconds INTEGER       NOT NULL,
    head_info        TEXT          NULL,
    head_db_name     VARCHAR(128)  NULL,         -- 头阻塞者所在库（留痕时定格；历史筛选用）
    chain_tree       TEXT          NOT NULL,     -- 最近一次链路快照 JSON
    resolved         BOOLEAN       NOT NULL DEFAULT FALSE,
    create_time      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    update_time      TIMESTAMPTZ   NULL
);

CREATE TABLE IF NOT EXISTS dbpilot_missing_index_snapshot (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id         INTEGER        NOT NULL,
    db_name             VARCHAR(128)   NOT NULL,
    table_name          VARCHAR(256)   NOT NULL,
    equality_columns    TEXT           NULL,
    inequality_columns  TEXT           NULL,
    included_columns    TEXT           NULL,
    user_seeks          BIGINT         NOT NULL,
    avg_total_user_cost DOUBLE PRECISION NOT NULL,
    avg_user_impact     DOUBLE PRECISION NOT NULL,
    score               DOUBLE PRECISION NOT NULL,
    last_user_seek      TIMESTAMPTZ    NULL,
    table_pages         INTEGER        NULL,
    table_rows          BIGINT         NULL,
    create_index_sql    TEXT           NOT NULL,
    snapshot_time       TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dbpilot_index_usage_snapshot (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id     INTEGER        NOT NULL,
    db_name         VARCHAR(128)   NOT NULL,
    table_name      VARCHAR(256)   NOT NULL,
    index_name      VARCHAR(256)   NOT NULL,
    is_primary_key  BOOLEAN        NOT NULL,
    is_unique       BOOLEAN        NOT NULL,
    type_desc       VARCHAR(60)    NOT NULL,
    user_seeks      BIGINT         NOT NULL,
    user_scans      BIGINT         NOT NULL,
    user_lookups    BIGINT         NOT NULL,
    user_updates    BIGINT         NOT NULL,
    last_user_seek  TIMESTAMPTZ    NULL,
    last_user_scan  TIMESTAMPTZ    NULL,
    key_columns     TEXT           NULL,
    used_page_count BIGINT         NULL,
    last_user_update TIMESTAMPTZ   NULL,
    avg_fragmentation_percent DOUBLE PRECISION NULL,
    is_unused       BOOLEAN        NOT NULL DEFAULT FALSE,
    snapshot_time   TIMESTAMPTZ    NOT NULL DEFAULT now()
);

-- 查询计划快照：每 (实例, 指纹, plan_hash) 一行；累计值每拍刷新，XML 首见时抓一份
CREATE TABLE IF NOT EXISTS dbpilot_query_plan (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id          INTEGER       NOT NULL,
    fingerprint          VARCHAR(64)   NOT NULL,      -- query_hash hex（与 top_sql_delta 同口径，NULL 兜底 sql_handle）
    db_name              VARCHAR(128)  NULL,
    query_plan_hash      VARCHAR(32)   NOT NULL,      -- 16 hex 小写
    plan_xml             TEXT          NULL,          -- 首次发现时从缓存抓；>1MB 存 NULL（驱逐后无从补抓）
    compile_time_utc     TIMESTAMPTZ   NULL,          -- qs.creation_time（实例时区已换算 UTC）
    first_seen_utc       TIMESTAMPTZ   NOT NULL,
    last_seen_utc        TIMESTAMPTZ   NOT NULL,
    execution_count      BIGINT        NOT NULL DEFAULT 0,   -- 该计划缓存累计，每拍刷新
    total_elapsed_ms     BIGINT        NOT NULL DEFAULT 0,
    total_worker_ms      BIGINT        NOT NULL DEFAULT 0,
    total_logical_reads  BIGINT        NOT NULL DEFAULT 0,
    create_time          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_dbpilot_qp UNIQUE (instance_id, fingerprint, query_plan_hash)
);

-- 计划变更事件：同指纹出现新 plan_hash 时一条（老/新计划各自累计均值，检测时固化）
CREATE TABLE IF NOT EXISTS dbpilot_plan_change (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id       INTEGER       NOT NULL,
    fingerprint       VARCHAR(64)   NOT NULL,
    db_name           VARCHAR(128)  NULL,
    old_plan_hash     VARCHAR(32)   NULL,
    new_plan_hash     VARCHAR(32)   NOT NULL,
    old_avg_elapsed_ms BIGINT       NULL,             -- 老计划累计总量的均值（无老计划/除零为 NULL）
    new_avg_elapsed_ms BIGINT       NULL,
    old_avg_worker_ms  BIGINT       NULL,
    new_avg_worker_ms  BIGINT       NULL,
    old_avg_reads      BIGINT       NULL,
    new_avg_reads      BIGINT       NULL,
    old_exec_count     BIGINT       NULL,
    new_exec_count     BIGINT       NULL,
    changed_at_utc    TIMESTAMPTZ    NOT NULL,         -- 新计划 compile_time（兜底采集时间）
    create_time       TIMESTAMPTZ    NOT NULL DEFAULT now()
);

-- Top SQL 指纹黑名单（全局：query_hash 对相同脚本跨实例稳定；页面"排除"按钮写入）
CREATE TABLE IF NOT EXISTS dbpilot_top_sql_exclusion (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint VARCHAR(64)   NOT NULL,
    sql_head    VARCHAR(500)  NULL,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- 实例性能指标分钟快照（MT-01 趋势页，10s 采集 / 保留 30 天）：
-- 瞬时列（cpu/mem/ple/命中率/连接/阻塞）直接填；率列 = 累计值相邻两拍差值÷间隔秒
CREATE TABLE IF NOT EXISTS dbpilot_instance_metrics (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id               INTEGER        NOT NULL,
    sample_time               TIMESTAMPTZ    NOT NULL,
    cpu_usage_pct             NUMERIC(5,2)   NULL,
    mem_usage_pct             NUMERIC(5,2)   NULL,
    os_total_memory_kb        BIGINT         NULL,
    os_available_memory_kb    BIGINT         NULL,
    sql_memory_kb             BIGINT         NULL,
    qps                       NUMERIC(12,2)  NULL,
    tps                       NUMERIC(12,2)  NULL,
    logins_sec                NUMERIC(12,2)  NULL,
    compilations_sec          NUMERIC(12,2)  NULL,
    recompilations_sec        NUMERIC(12,2)  NULL,
    full_scans_sec            NUMERIC(12,2)  NULL,
    lazy_writes_sec           NUMERIC(12,2)  NULL,
    ple                       INTEGER        NULL,
    buffer_cache_hit_ratio_pct NUMERIC(5,2)  NULL,
    deadlocks_sec             NUMERIC(12,2)  NULL,
    lock_timeouts_sec         NUMERIC(12,2)  NULL,
    lock_waits_sec            NUMERIC(12,2)  NULL,
    user_connections          INTEGER        NULL,
    blocked_processes         INTEGER        NULL,
    iops_read                 NUMERIC(12,2)  NULL,
    iops_write                NUMERIC(12,2)  NULL,
    mbps_read                 NUMERIC(10,3)  NULL,
    mbps_write                NUMERIC(10,3)  NULL
);

-- 磁盘卷用量快照（每卷一行）
CREATE TABLE IF NOT EXISTS dbpilot_instance_disk (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id         INTEGER       NOT NULL,
    volume_mount_point  VARCHAR(260)  NOT NULL,
    total_mb            BIGINT        NULL,
    available_mb        BIGINT        NULL,
    used_pct            NUMERIC(5,2)  NULL,
    sample_time         TIMESTAMPTZ   NOT NULL
);

-- 二级索引独立创建（PG 索引不内联进建表语句；IF NOT EXISTS 幂等，与表级 IF NOT EXISTS 同口径）
CREATE INDEX IF NOT EXISTS ix_ars ON dbpilot_active_request_sample (instance_id, minute_time DESC);
CREATE INDEX IF NOT EXISTS ix_tsd ON dbpilot_top_sql_delta (instance_id, window_start, fingerprint);
CREATE INDEX IF NOT EXISTS ix_ss ON dbpilot_slow_sql (instance_id, event_time, duration_ms DESC);
CREATE INDEX IF NOT EXISTS ix_dl ON dbpilot_deadlock_event (instance_id, event_time DESC);
CREATE INDEX IF NOT EXISTS ix_dlp ON dbpilot_deadlock_process (instance_id, event_time DESC);
CREATE INDEX IF NOT EXISTS ix_dlp_event ON dbpilot_deadlock_process (event_id);
CREATE INDEX IF NOT EXISTS ix_dlr ON dbpilot_deadlock_resource (instance_id, event_time DESC);
CREATE INDEX IF NOT EXISTS ix_dlr_event ON dbpilot_deadlock_resource (event_id);
CREATE INDEX IF NOT EXISTS ix_bl ON dbpilot_blocking_event (instance_id, start_time DESC);
CREATE INDEX IF NOT EXISTS ix_mi ON dbpilot_missing_index_snapshot (instance_id, db_name, snapshot_time DESC);
CREATE INDEX IF NOT EXISTS ix_iu ON dbpilot_index_usage_snapshot (instance_id, db_name, snapshot_time DESC);
CREATE INDEX IF NOT EXISTS ix_qp_fp ON dbpilot_query_plan (instance_id, fingerprint);
CREATE INDEX IF NOT EXISTS ix_pc_time ON dbpilot_plan_change (instance_id, changed_at_utc DESC);
CREATE INDEX IF NOT EXISTS ix_pc_fp ON dbpilot_plan_change (instance_id, fingerprint);
CREATE UNIQUE INDEX IF NOT EXISTS ux_tse ON dbpilot_top_sql_exclusion (fingerprint);
CREATE INDEX IF NOT EXISTS ix_im ON dbpilot_instance_metrics (instance_id, sample_time);
CREATE INDEX IF NOT EXISTS ix_idisk ON dbpilot_instance_disk (instance_id, sample_time);
